# Generated by Django 5.1.7 on 2025-03-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_alter_resume_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="uplaoded_at",
            new_name="uploaded_at",
        ),
    ]
